fix(package.json): move astro from dependencies to peerDependencies (#668)
* fix(package.json): move astro from dependencies to peerDependencies

* chore(knip.config.ts): enable astro plugin manually

* test(tests/e2e/fixtures/package.json): add astro to dependencies

* test(tests/e2e/fixtures/bun.lockb): update lockfile

* chore(knip.config.ts): remove ignoreBinaries in test fixtures workspace

* fix(package.json): add carets to dependency versions

* fix(package.json): loose peerDependencies version constraint and add astro to devDependencies

* chore(renovate.json5): disable version pinning for dependencies and peerDependencies

* ci(.github/workflows/e2e.yml): handle multiple versions of astro

* ci(.github/workflows/lint.yml): add job to conclude the result

* ci(.github/workflows/lint.yml): run actions-timeline after lint-status

* ci(.github/workflows/lint.yml): handle skipped and cancelled status for conclusion job

* ci(.github/workflows/lint.yml): fix if statement in bash script

* ci(.github/workflows/lint.yml): fix check status bash script

* ci(.github/workflows/lint.yml): split actions-timeline job

* ci(.github/workflows/e2e.yml): test several astro versions in the fixture

* fix(package.json): narrow astro peerDependencies range

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -14,11 +14,54 @@ defaults:
     shell: bash
 
 jobs:
-  test-e2e-general:
+  list-astro-versions:
     runs-on: ubuntu-24.04
     timeout-minutes: 10
     permissions:
       contents: read # for checkout
+
+    outputs:
+      astro-versions: ${{ steps.list.outputs.versions }}
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
+
+      - name: Install mise
+        uses: jdx/mise-action@f8dfbcc150159126838e44b882bf34bd98fd90f3 # v2.1.0
+        with:
+          experimental: true
+          install: false
+
+      - name: Install mise tools
+        # cspell:ignore reshim
+        # reshim is required to avoid "No such file or directory" error
+        # ref: https://github.com/jdx/mise/issues/2260
+        run: mise install || (mise reshim && mise install)
+
+      - name: Install package.json dependencies
+        run: mise run buni
+
+      - name: List astro versions for E2E tests
+        id: list
+        run: |
+          versions=$(bun run .github/workflows/scripts/list-astro-versions.ts)
+          echo "versions=$versions" >> "$GITHUB_OUTPUT"
+
+  test-e2e-general:
+    needs:
+      - list-astro-versions
+
+    runs-on: ubuntu-24.04
+    timeout-minutes: 10
+    permissions:
+      contents: read # for checkout
+
+    name: test-e2e-general-astro-${{ matrix.version }}
+    strategy:
+      fail-fast: false
+      matrix:
+        version: ${{ fromJson(needs.list-astro-versions.outputs.astro-versions) }}
 
     steps:
       - name: Checkout
@@ -43,7 +86,7 @@ jobs:
         run: mise run build
 
       - name: Install E2E Test Fixtures Dependencies
-        run: bun install --frozen-lockfile
+        run: bun install astro@${{ matrix.version }}
         working-directory: tests/e2e/fixtures
 
       - name: Build E2E Test Fixtures with astro-better-image-service
@@ -89,7 +132,7 @@ jobs:
         if: failure() && steps.playwright-test.outcome == 'failure'
         uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
         with:
-          name: playwright-report-${{ github.sha }}
+          name: playwright-report-astro-${{ matrix.version }}-${{ github.sha }}
           path: playwright-report/
 
   test-e2e-conversion:
@@ -124,7 +167,12 @@ jobs:
         id: dependency-versions
         run: |
           playwright_version=$(bun pm ls | sed -nE 's/.*@playwright\/test@(.+)/\1/p')
-          astro_version=$(bun pm ls | sed -nE 's/.*astro@(.+)/\1/p')
+          astro_version=$(bun pm ls | sed -nE 's/.*astro@(.+)/\1/p' | uniq)
+          # throw error if several versions are found
+          if [[ $(echo "$astro_version" | wc -l) -gt 1 ]]; then
+            echo "Multiple versions of Astro found: $astro_version"
+            exit 1
+          fi
           echo "playwright=$playwright_version" >> "$GITHUB_OUTPUT"
           echo "astro=$astro_version" >> "$GITHUB_OUTPUT"
 
@@ -203,13 +251,31 @@ jobs:
           name: playwright-report-conversion-${{ github.sha }}
           path: playwright-report/
 
-  actions-timeline:
+  test-e2e-status:
     needs:
       - test-e2e-general
       - test-e2e-conversion
 
     # skip if the workflow is called from another workflow
     if: ${{ !cancelled() && contains(github.workflow_ref, '/e2e.yml') }}
+
+    runs-on: ubuntu-24.04
+    timeout-minutes: 5
+
+    steps:
+      - name: Check the status of the jobs
+        run: |
+          if [[ $(echo '${{ toJson(needs.*.result) }}' | jq 'all(. == "success")') == "false" ]]; then
+            echo 'Some jobs are failed, cancelled, or skipped.'
+            exit 1
+          fi
+          echo 'All jobs are successful.'
+
+  actions-timeline:
+    needs:
+      - test-e2e-status
+
+    if: needs.test-e2e-status.result == 'success' || needs.test-e2e-status.result == 'failure'
 
     runs-on: ubuntu-24.04
     timeout-minutes: 5
