ci(.github/workflows/lint.yml): handle skipped and cancelled status for conclusion job

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -164,23 +164,6 @@ jobs:
 
     runs-on: ubuntu-24.04
     timeout-minutes: 5
-
-    steps:
-      - name: All jobs passed
-        if: ${{ !(contains(needs.*.result, 'failure')) }}
-        run: exit 0
-      - name: Some jobs failed
-        if: ${{ contains(needs.*.result, 'failure') }}
-        run: exit 1
-
-  actions-timeline:
-    needs:
-      - lint-status
-
-    if: ${{ !cancelled() }}
-
-    runs-on: ubuntu-24.04
-    timeout-minutes: 5
     permissions:
       actions: read
 
@@ -188,3 +171,13 @@ jobs:
       - name: actions-timeline
         # cspell:ignore kesin
         uses: Kesin11/actions-timeline@3046833d9aacfd7745c5264b7f3af851c3e2a619 # v2.2.1
+
+      - name: Check the status of the jobs
+        run: |
+          if [[ echo '${{ toJson(needs.*.result) }}' | jq 'all(. == "success")' ]]; then
+            echo "All jobs are successful."
+            exit 0
+          else
+            echo "Some jobs are failed, cancelled, or skipped."
+            exit 1
+          fi
