Revert "chore: update linters and ci (#1065)"
This reverts commit 73021363c7ec67abf424c23f50f9b5d2a45a748b.

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -2,12 +2,10 @@ name: Lint
 
 on:
   pull_request:
-    branches:
-      - main
   workflow_call:
   workflow_dispatch:
   schedule:
-    - cron: "0 0 * * SUN"
+    - cron: '0 0 * * SUN'
 
 permissions: {}
 
@@ -28,24 +26,27 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          persist-credentials: false
 
       - name: Install mise
         uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
         with:
-          version: 2025.1.0
-          cache_save: ${{ github.ref_name == 'main' }}
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
+          experimental: true
+          install: false
+
+      - name: Install mise tools
+        # cspell:ignore reshim
+        # reshim is required to avoid "No such file or directory" error
+        # ref: https://github.com/jdx/mise/issues/2260
+        run: mise install || (mise reshim && mise install)
+
+      - name: Install package.json dependencies
+        run: mise run buni
 
       - name: List mise tasks
         id: list
         run: |
-          tasks=$(mise tasks ls --json \
-            | jq --raw-output --compact-output \
-              'map(select(.name | test("^check:")) | {name: (.name | sub("^.+:" ; "")), task: .name})')
-          echo "tasks=${tasks}" >> "${GITHUB_OUTPUT}"
+          tasks=$(bun run .github/workflows/scripts/list-mise-tasks.ts)
+          echo "tasks=$tasks" >> "$GITHUB_OUTPUT"
 
   lint:
     needs: list-tasks
@@ -55,7 +56,7 @@ jobs:
     permissions:
       contents: read # for checkout
 
-    name: ${{ matrix.name }}
+    name: lint-${{ matrix.name }}
     strategy:
       fail-fast: false
       matrix:
@@ -66,23 +67,30 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          persist-credentials: false
 
       - name: Install mise
         uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
         with:
-          version: 2025.1.0
-          cache_save: ${{ github.ref_name == 'main' }}
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
+          experimental: true
+          install: false
+
+      - name: Install mise tools
+        # cspell:ignore reshim
+        # reshim is required to avoid "No such file or directory" error
+        # ref: https://github.com/jdx/mise/issues/2260
+        run: mise install || (mise reshim && mise install)
+
+      - name: Install mise tools
+        run: mise install --verbose
+
+      - name: Install package.json dependencies
+        if: matrix.buni
+        run: mise run buni
 
       - name: Run ${{ matrix.name }}
         run: mise run ${{ matrix.task }}
-        env:
-          LINT: true
 
-  commitlint:
+  lint-commitlint:
     runs-on: ubuntu-24.04
     timeout-minutes: 10
     permissions:
@@ -93,15 +101,18 @@ jobs:
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
           fetch-depth: 0 # fetch all history for commitlint
-          persist-credentials: false
 
       - name: Install mise
         uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
         with:
-          version: 2025.1.0
-          cache_save: ${{ github.ref_name == 'main' }}
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
+          experimental: true
+          install: false
+
+      - name: Install mise tools
+        # cspell:ignore reshim
+        # reshim is required to avoid "No such file or directory" error
+        # ref: https://github.com/jdx/mise/issues/2260
+        run: mise install || (mise reshim && mise install)
 
       - name: Install package.json dependencies
         run: mise run buni
@@ -131,18 +142,37 @@ jobs:
         # ref: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
         env:
           PR_TITLE: ${{ github.event.pull_request.title }}
-        run: echo "${PR_TITLE}" | bun run commitlint --verbose
+        run: echo "$PR_TITLE" | bun run commitlint --verbose
 
       - name: commitlint (last commit)
         if: steps.commitlint-push-initial.outcome == 'skipped' && steps.commitlint-push.outcome == 'skipped' && steps.commitlint-pr.outcome == 'skipped'
         run: bun run commitlint --verbose --from ${{ github.sha }}~1 --to ${{ github.sha }}
 
-  actions-timeline:
+  lint-status:
     needs:
       - lint
-      - commitlint
+      - lint-commitlint
+
     # skip if the workflow is called from another workflow
     if: ${{ !cancelled() && contains(github.workflow_ref, '/lint.yml') }}
+
+    runs-on: ubuntu-24.04
+    timeout-minutes: 5
+
+    steps:
+      - name: Check the status of the jobs
+        run: |
+          if [[ $(echo '${{ toJson(needs.*.result) }}' | jq 'all(. == "success")') == "false" ]]; then
+            echo 'Some jobs are failed, cancelled, or skipped.'
+            exit 1
+          fi
+          echo 'All jobs are successful.'
+
+  actions-timeline:
+    needs:
+      - lint-status
+
+    if: needs.lint-status.result == 'success' || needs.lint-status.result == 'failure'
 
     runs-on: ubuntu-24.04
     timeout-minutes: 5
